name: 'notification-server'
dependencies:
  browser: any
  angular: '0.12.0'
  vader:
    git:
      url: git@bitbucket.org:atende/wu-vader.git
      ref: develop
  highcharts4dart:
    git:
      url: https://github.com/giovannicandido/highcharts4dart.git